
INSERT INTO RENTAL_CHARGE (TOOL_TYPE, DAILY_CHARGE, IS_CHARGED_ON_WEEKDAYS, IS_CHARGED_ON_WEEKENDS, IS_CHARGED_ON_HOLIDAYS) VALUES ('Ladder', 1.99, true, true, false);
INSERT INTO RENTAL_CHARGE (TOOL_TYPE, DAILY_CHARGE, IS_CHARGED_ON_WEEKDAYS, IS_CHARGED_ON_WEEKENDS, IS_CHARGED_ON_HOLIDAYS) VALUES ('Chainsaw', 1.49, true, false, true);
INSERT INTO RENTAL_CHARGE (TOOL_TYPE, DAILY_CHARGE, IS_CHARGED_ON_WEEKDAYS, IS_CHARGED_ON_WEEKENDS, IS_CHARGED_ON_HOLIDAYS) VALUES ('Jackhammer', 2.99, true, false, false);

INSERT INTO TOOL (TOOL_CODE, BRAND, TOOL_TYPE) VALUES ('LADW', 'Werner', 'Ladder');
INSERT INTO TOOL (TOOL_CODE, BRAND, TOOL_TYPE) VALUES ('CHNS', 'Stihl', 'Chainsaw');
INSERT INTO TOOL (TOOL_CODE, BRAND, TOOL_TYPE) VALUES ('JAKR', 'Ridgid', 'Jackhammer');
INSERT INTO TOOL (TOOL_CODE, BRAND, TOOL_TYPE) VALUES ('JAKD', 'DeWalt', 'Jackhammer');